default: &default
  adapter: sqlite3
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: wookiee_date_development

test:
  <<: *default
  database: wookiee_date_test

production:
  <<: *default
  database: wookiee_date_production
  username: wookiee_date
  password: <%= ENV['WOOKIEE_DATE_DATABASE_PASSWORD'] %>
